name: Publish to PyPI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2 # 检出代码仓库

    - name: Set up Python
      uses: actions/setup-python@v2 # 设置Python环境
      with:
        python-version: 3.11 # 选择适合你的Python版本

    - name: Get the commit hash and create version
      id: get_version
      run: |
        COMMIT_HASH=$(git rev-parse --short HEAD)
        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "RELEASE_TAG=0.0.0.dev$COMMIT_COUNT+g$COMMIT_HASH" >> $GITHUB_ENV
      # 创建符合 PEP 440 的开发版本号，格式：0.0.0.devN+gHASH

    - name: Replace THE_VERSION in setup.py with the commit hash
      run: |
        sed -i "s/THE_VERSION/${{ env.RELEASE_TAG }}/g" setup-preview.py
        sed -i "s/THE_VERSION/${{ env.RELEASE_TAG }}/g" haaaash/__init__.py
        # 使用提交哈希值替换 setup.py 中的 THE_VERSION

    - name: Build and upload to PyPI
      run: |
        sed -i "s/IS/haaaash-preview/g" haaaash/__init__.py
        pip install --upgrade setuptools wheel
        python setup-preview.py sdist bdist_wheel # 构建项目并创建包
        pip install twine # 安装Twine以便上传到PyPI
        twine upload dist/* # 使用Twine上传包到PyPI
      env:
        TWINE_USERNAME: __token__ # 使用PyPI API令牌，用户名为 "__token__"
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }} # 使用GitHub仓库的密钥存储的PyPI API令牌
